apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gamani
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - gamani.vadimzak.com
    secretName: gamani-tls
  rules:
  - host: gamani.vadimzak.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gamani
            port:
              number: 80
