apiVersion: v1
kind: Service
metadata:
  name: gamani-service
  namespace: apps
  labels:
    app: gamani
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3002
    protocol: TCP
    name: http
  selector:
    app: gamani