apiVersion: v1
kind: ServiceAccount
metadata:
  name: gamani-service-account
  namespace: apps
  annotations:
    # For IRSA (IAM Roles for Service Accounts) when using EKS
    # This annotation maps the Kubernetes service account to an AWS IAM role
    eks.amazonaws.com/role-arn: arn:aws:iam::363397505860:role/gamani-app-role
  labels:
    app: gamani
---
# ClusterRole for minimal required Kubernetes permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gamani-role
  namespace: apps
rules:
# Minimal permissions - only what the app needs
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
---
# Bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gamani-role-binding
  namespace: apps
subjects:
- kind: ServiceAccount
  name: gamani-service-account
  namespace: apps
roleRef:
  kind: Role
  name: gamani-role
  apiGroup: rbac.authorization.k8s.io