apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - deployment.yaml
  - service.yaml
  - service-account.yaml
  - ingress.yaml

commonLabels:
  app: test1
  environment: production
