version: '3.8'

services:
  sample-app:
    # container_name is set dynamically by deployment script
    image: sample-app:latest
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env.production
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Scheduled tasks runner
  cron-tasks:
    # container_name is set dynamically by deployment script
    image: sample-app:latest
    restart: unless-stopped
    command: ["node", "cron/scheduler.js"]
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    networks:
      - app-network
    depends_on:
      - sample-app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

networks:
  app-network:
    external: true
    name: sample-app_app-network