global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'bf-backend-monitor'

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor for Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metric_relabel_configs:
      # Keep only essential metrics to reduce storage
      - source_labels: [__name__]
        regex: '(container_cpu_usage_seconds_total|container_memory_usage_bytes|container_memory_rss|container_network_receive_bytes_total|container_network_transmit_bytes_total|container_fs_usage_bytes|container_fs_limit_bytes)'
        action: keep

  # Docker daemon metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['172.17.0.1:9323']

  # Dynamic app discovery through Docker labels
  - job_name: 'apps'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s
    relabel_configs:
      # Only monitor containers with prometheus.enable=true label
      - source_labels: [__meta_docker_container_label_prometheus_enable]
        regex: true
        action: keep
      # Use container name as instance
      - source_labels: [__meta_docker_container_name]
        target_label: instance
      # Extract app name from container label
      - source_labels: [__meta_docker_container_label_app_name]
        target_label: app
      # Extract service type from container label
      - source_labels: [__meta_docker_container_label_service_type]
        target_label: service_type
      # Set metrics path from label or default to /metrics
      - source_labels: [__meta_docker_container_label_prometheus_path]
        regex: (.+)
        target_label: __metrics_path__
      # Extract port from label or default to 3001
      - source_labels: [__address__, __meta_docker_container_label_prometheus_port]
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - source_labels: [__address__]
        regex: ([^:]+)(?::\d+)?
        replacement: $1:3001
        target_label: __address__